[package]
name = "casper-binary-port-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-binary-port = { path = "../casper-node/binary_port" }
casper-types = { version = "5.0.0", path = "../casper-node/types", features = [
    "datasize",
    "json-schema",
    "std",
] }
clap = { version = "4.5.3", features = ["derive"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net"] }
bytes = "1.5.0"
hex = "0.4.3"
tokio-util = { version = "0.6.4", features = ["codec"] }
futures = "0"
