[workspace]
resolver = "2"
members = ["binary_port_access"]

[package]
name = "casper-binary-port-client"
version = "0.1.0"
edition = "2021"
authors = ["Rafał Chabowski <rafal@casperlabs.io>"]
description = "CLI for Casper binary port."
license = "Apache-2.0"

# TODO[RC]: Review what is still needed after moving parts of the code to "lib".
[dependencies]
casper-binary-port = { path = "../casper-node/binary_port" }
casper-types = { version = "5.0.0", path = "../casper-node/types", features = [
    "datasize",
    "json-schema",
    "std",
    "std-fs-io",
] }
casper-binary-port-access = { path = "./binary_port_access"}
clap = { version = "4.5.3", features = ["derive", "wrap_help"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net"] }
bytes = "1.5.0"
hex = "0.4.3"
tokio-util = { version = "0.6.4", features = ["codec"] }
futures = "0"
