name: CI Pipeline

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      # Build using Makefile
      - name: Build the project
        run: make build

      - name: Run tests
        run: make test

      - name: Run Clippy linter
        run: make lint

      # - name: Run Clippy linter for wasm target
      #   run: make lint-wasm

      - name: Check code formatting
        run: make fmt-check

      - name: Run security audit
        run: make audit
